---
title: "Auto-Stats Description"
author: "Arne John"
date: "2024-07-15"
output: html_document
---


## AssumptionChecksContainer


```{r setup, include=TRUE, run = FALSE}
  container <- jaspResults[["AssumptionChecks"]] # TO DO: Take notes on worked code, hand in like assignment
  # Overcome delays by seeing it as 
```

My idea here is to copy the set-up of mainTableData and "port it over" into a new table for the assumptions. 
It again goes into the fill functions, as there the test are ordered as a list 

Adding jaspResults into the input for .ttestIndependentEqVarFill to create jaspStates

Tried adapting the list from .ttestIndependentNormalFill into the data frame approach, failed to do so.

Same has to happen for descriptives

! Adding in the name of the test in order to refer to the right data in 5. Hypothesis testing

 # TO DO: Take notes on worked code, hand in like assignment
  # Overcome delays by seeing it as a homework report to be turned in at the end of the week. Can be as plain as is, can be funny. 
  # Just to report on what I've done and not feel anxious. 
  # For the code, copy the format from mainTable and fill it in, but with more eloquence, so that by the time the last section comes around, the comments can be minimal

Note for programmers: A data.table saved as a jaspObject does not retain its rownames

You finishing your degree comes over perfectionism. 

## QML Buttons connect

Look up front-end technique button sync, apply it for QML. It's JavaScript-esque, as far as I understand. Copy steps here for report text. 